### ISSUE TITLE
"inline" is not accepted as an attribute name

### ISSUE THREAD

**Issue by rlepigre** [rems-project/cerberus#181]
The following example currently does not parse:
```c
[[inline]]
int main() {
  return 0;
}
```

**Comment by kmemarian** [comment]
a705868 should fix the issue.

I added support for all C keyword as this seems to be the intent of the spec, but I did it in a rather silly way. Do you know if there is a better way to recover the string of a token from within a menhir parser?

**Comment by rlepigre** [comment]
I had a quick look at the doc, but could not find a better solution. The only thing I thought about was to use the `keywords` list in the lexer file to compute the string from the token. But that does not really help, since you would still need to write the token name twice. I guess this will have to do. :)

Thanks for looking into this though!
