### ISSUE TITLE
Fails to build with sexplib0 v0.15.0

### ISSUE THREAD

**Issue by MackieLoeffel** [rems-project/cerberus#194]
`sexp_opaque` was removed in sexplib0 v0.15.0 which breaks the build of cerberus:

https://github.com/janestreet/sexplib0/compare/v0.14.0...v0.15.0#diff-c313d3993c2c51930ec40df95a7439681bc57429e7039c83cde2b7d2d57c3defL11

**Comment by kmemarian** [comment]
fixed in c4251f23dd402aa5b34b13127d0960e1dfd7baa9
