### ISSUE TITLE
magic comments/attributes

### ISSUE THREAD

**Issue by cp526** [rems-project/cerberus#195]
It would be great to have magic comment/attribute support for the following places:
- [x] for function definitions, in-between the list of arguments and (the opening curly brace of) the function body
- [x] inside function bodies, in all places where statements are allowed
- [x] in loops, in-between the loop condition and (the opening curly brace of) the loop body

**Comment by kmemarian** [comment]
I've added preliminary code for this in ec7d5aaff933f45c580cdeb45e865e4ecc7c4a52. For now it only does the parsing and turns each magic comment into a dummy `cerb::magic()` attribute.

The magic comments before statements are not detected yet.

And for `do .. while()`, I wasn't sure where you'd want the them to be allowed.
