### ISSUE TITLE
Incorrect constraint simplification

### ISSUE THREAD

**Issue by yav** [rems-project/cerberus#227]
I tried CN at this commit: a6e088fca806bd94

I tried it on the following example:
```c
signed int add_2(signed int x, signed int y)                                     
/*@ requires x == 0i32 @*/                                                          
/*@ ensures return == y @*/                                                         
{                                                                                
  return x + y;                                                                  
}
```
I run:
```
cn test.c --state-file=out.html
```
This results in:
```
[1/1]: add_2
test.c:5:3: error: Unprovable constraint
  return x + y;
  ^~~~~~~~~~~~~ 
Constraint from (test.c:3:10:)
Consider the state in out.html
```
When I look in `out.html`  I see the following:

![image](https://github.com/rems-project/cerberus/assets/12394/c51c61cf-5fea-4220-b752-9c91ec8654b9)

The constraint on the LHS looks OK, but the simplified version looks quite wrong.

**Comment by dc-mak** [comment]
That's embarrassing - should be fixed by https://github.com/rems-project/cerberus/commit/10506fa4f31c7302e2ab1ec1dd76002662fe5dcc

**Comment by yav** [comment]
I tried it and it works.  Thanks!
