### ISSUE TITLE
const object initialization and capability permissions

### ISSUE THREAD

**Issue by vzaliva** [rems-project/cerberus#229]
In CHERI C, pointers to constant objects should be
readonly-capabilities. Presently, it is not implemented. One
peculiarity of this problem is that while we need to be able to write
the results of the initialization, the initializer itself could have
access to the pointer to the object being initialized. A naive
approach could lead to undesirable writable capability copy stealing
scenarios.

# Examples

```
    int *p;
    
    int main(void)
    {
      const int x = (p = (int*)&x, 42);
      *p = 22; // UB
      return x;
    }

    let strong x: pointer = create(Ivalignof('signed int'), 'signed int') in
    let strong a_509: loaded integer =
      bound(
        let strong _: loaded pointer =
          let weak (a_510: pointer, a_515: loaded pointer) =
            unseq(
              pure(p)
            ,
              let weak a_511: loaded pointer =
                let weak a_513: pointer = pure(x) in
                pure(Specified(a_513)) in
              case a_511 of
                | Specified(a_512: pointer) =>
                    let weak a_514: boolean =
                      memop(PtrWellAligned, 'signed int', a_512) in
                    pure(
                      Specified(if a_514
                      then a_512
                      else undef(<<UB025_misaligned_pointer_conversion>>))
                    )
                | Unspecified(_: ctype) =>
                    pure(undef(<<UB025_misaligned_pointer_conversion>>))
              end
            ) in
          let weak _: unit = neg(store('signed int*', a_510, a_515)) in
          pure(a_515) in
        pure(Specified(42))
      ) in
    store_lock('signed int', x, conv_loaded_int('signed int', a_509)) ;
```

Another example:

```
    int *p;
    
    int func(int *q)
    {
      p = q;
      return 42;
    }
    
    int main(void)
    {
      const int x = func((int*)&x);
      *p = 22; // UB
      return x;
    }  
```

# Proposal

## *Core* elaboration

Currently, the *Core* code generated does the following:

1.  Call `create`, which allocates an object and returns a pointer `p` with r/w allocation and capability.
2.  Perform initialization to calculate the initialization value. This may refer to `p`.
3.  Call `store_lock` to store the result of the initialization at `p` and change the allocation status to read-only.

The new proposed Core elaboration:

1.  Call `create`, which allocates an object and returns a temporary pointer `p_rw` with r/w allocation and capability.
2.  Make a read-only copy of the pointer: `p = intrinsic_perms_and(!rwRW, p_rw)`
3.  Perform initialization to calculate the initialization value. This may refer to `p`.
4.  Call `store_lock` to store the result of the initialization at `p_rw` and change the allocation status to read-only.

(After this step, `p_rw` should never be used again.)

Pseudo-code:

```
    let strong x_rw: pointer = create ()
    let strong x: pointer = intrinsic_perms_and(~rwRW, p_rw)
    let strong initval = (* initializer code which could could reference p but not p_rw *)
    store_lock p_rw initval
```

From the implementation point of view, this could all be
implemented in elaboration and will not require changes to the
memory model implementation or interface.

An alternative to calling the intrinsic is to change `create` to
return a tuple `(p, p_rw)` but this will require changes to memory
model implementation. The benefit of this is that the same
elaboration could be used for both CHERI and *concrete* memory
models. For *concrete*, returned `p` and `p_rw` will be the same.

## Compilation

If we are to implement something like this in Clang, we can follow
roughly the same steps as the Core elaboration proposal, using two
capabilities: one writable and one read-only. After initialization
is complete, `p_rw` should be dropped by clearing the register or
stack slot, or invalidated by calling `intrinsic_tag_clear`.

There is a performance cost, caused by an additional operation to
clear permissions and possibly a call to clear the tag at the
end. Thus, this scheme should be used only for the initialization
of *const* objects.

## Proof considerations

From the point of view of an abstract C machine, the temporary
pointer `p_rw` is not visible, and the whole object allocation and
initialization is a single operation.

If we are going to reason about generated *Core* code, we will need
to prove that `p_rw` is used only once after initialization (in
`store_lock`) and not copied or stored elsewhere.

Finally, if we are going to reason about generated machine code, we
will need to make sure any code called between allocation and
`store_lock` does not have access to `p_rw` (regardless of where it was
stored: on the stack or in a register) and after `store_lock`, `p_rw`
is no longer accessible (dropped or its tag is cleared).

**Comment by kmemarian** [comment]
fixed by mergin PRs #576 and #577.
