### ISSUE TITLE
CN crash caused by division `/` and modulus `%`

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#231]
Running CN on a program that uses the C division operator `/` or modulus operator `%` causes it to crash. 

I'm using this commit: [5d8a2fb88](https://github.com/rems-project/cerberus/commit/5d8a2fb88fa1d010d3f6f3d165038aec0ac7f4de)

We need `/` for the binary search example [here](https://github.com/GaloisInc/VERSE-Toolchain/blob/36-bug-fix-cn-introsimple_examplesc/cn-intro/dafny_examples.c). This previously worked in CN as of January-ish, so this appears to be a regression. 

Instructions to replicate: 

1. Run CN on this program: 
```
int main() {
  int i; 
  i = 1/1; // same for 1%1
}
``` 
2. Result: 
```
[1/1]: main
cn: internal error, uncaught exception:
    Failure("todo")
    Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
    Called from Dune__exe__Typing.pure in file "backend/cn/typing.ml", line 102, characters 22-25
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.pure in file "backend/cn/typing.ml", line 102, characters 22-25
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.pure in file "backend/cn/typing.ml", line 102, characters 22-25
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.bind in file "backend/cn/typing.ml", line 78, characters 8-11
    Called from Dune__exe__Typing.run in file "backend/cn/typing.ml", line 44, characters 16-19
    Called from Dune__exe__Main.main in file "backend/cn/main.ml", line 183, characters 20-87
    Called from Dune__exe__Main.main in file "backend/cn/main.ml", line 179, characters 9-1023
    Re-raised at Dune__exe__Main.main in file "backend/cn/main.ml", line 223, characters 8-73
    Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
    Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

Desired behavior: 

Either: 
* Division / modulus now unsupported -> a proper error message is generated 
* Division / modulus should work -> CN reasons about them properly

**Comment by septract** [comment]
The same mystery error comes up when using the `-=` assignment operator.

**Comment by kmemarian** [comment]
@cp526 the issue comes from the move to the Core builtin for `wrapI` and `catch_exceptional_condition` which didn't include a new elaboration for division or the rem operators. The `"todo"` failwith seems to start from fb37e1f08afaf03ba1b602d108ac6b89d418567a.

**Comment by septract** [comment]
This came up again in a MM conversation. How hard would it be to add elaborations for this and other missing operators?

**Comment by dc-mak** [comment]
@MedranoApol is working on this.
