### ISSUE TITLE
Error importing `stdio` with confusing "union types" message.

### ISSUE THREAD

**Issue by scuellar** [rems-project/cerberus#234]
**Description:**
When attempting to compile a file that imports the stdio library, the cn compiler fails with an unclear error message related to "union types".

**Steps to Reproduce:**
1. Create file `example.c` with
```
#include <stdio.h>
```
2. Run Cn
```
% cn example.c
```

**Expected Behavior:**
The file should be checked by `cn` without errors, or a more descriptive error message should be provided if there is an issue with the usage of stdio.

**Actual Behavior:**
The compilation fails, and the following error message is displayed:
```
unknown location  error: union types
```

**Additional Information:**

- **`cn` Version**: unknown
- **Operating System:** OSx 13.5.1 (22G90)

**Comment by dc-mak** [comment]
Being fixed in https://github.com/rems-project/cerberus/pull/238

**Comment by dc-mak** [comment]
Merged in https://github.com/rems-project/cerberus/commit/a1f0bbd0f808ea56b962a57b4292d1de0c4e28bb
