### ISSUE TITLE
[CN] Type error on good C code.

### ISSUE THREAD

**Issue by scuellar** [rems-project/cerberus#236]
**Description:**
CN reports a type error on correct C code. It seems like CN is making eager assumptions about the types of constants, which shouldn't be the case in C. 

**Steps to Reproduce:**
1. Create file `example.c` with
```
unsigned int type_error (unsigned int x) {
  return (-x)*0x4;
}
```
2. Run Cn
```
% cn example.c
```

**Expected Behavior:**
The file should type check correctly by `cn` and succeed. 

**Actual Behavior:**
The execution of `cn` fails, and the following error message is displayed:
```
error: Type error
  return (-x)*0x4;
         ^~~~ 
Expected value of type 'i32' but found value of type 'u32'
```

**Additional Information:**

- **`cn` Version**: unknown
- **Operating System:** OSx 13.5.1 (22G90)

**Comment by septract** [comment]
I wonder if this example has the same root cause: 
```
int
main()
{
	if (sizeof(int) - 2 < 0)
		return 1;
	return 0;
}
```
(Mimized from [this example](https://github.com/rems-project/cn-tutorial/blob/main/src/example-archive/c-testsuite/broken/error-proof/00038.err1.c))

Result: 
```
broken/error-proof/00038.err1.c:8:6: error: Type error
        if (sizeof(int) - 2 < 0)
            ~~~~~~~~~~~~^~~ 
Expected value of type 'u64' but found value of type 'u32'
```

**Comment by dc-mak** [comment]
Can you also add a regression test to the test directory for this?

**Comment by cp526** [comment]
already there in cn-tutorial

**Comment by dc-mak** [comment]
https://github.com/rems-project/cn-tutorial/commit/3453f6889c53af99f1bfad2f787d413907b8e483
