### ISSUE TITLE
[CN] syntax for negation

### ISSUE THREAD

**Issue by jwshii** [rems-project/cerberus#247]
(Ported from CN heuristic evaluation results.)
Two participants reported that they had difficulty figuring out the syntax for negation. 

In the context of the `abs` exercise in the tutorial, it takes a while to realize that you need to do something like `0i32 - x` or `-1i32 * x` instead of simply `-x` in the clause `ensures return == ((x >= 0i32) ? x : -x);`

It would be nice for negation either to be available more directly as `-x`, or if this is not possible, for the recommended alternative to be documented more explicitly in the tutorial or otherwise.

commit: `9a7b20e`

**Comment by dc-mak** [comment]
Should be fixed by https://github.com/rems-project/cerberus/commit/7f32664c2dce30707f50ec6f531106def4d59bb9
