### ISSUE TITLE
[CN] Type error when negating a `long` integer literal 

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#257]
CN version: 26a08ed5f9e1b5434e253d02061bd2f3e6cc12e2

Error case: 
```
// Type error: 
void a() { 
  -1l; 
  return; 
}
```

Result: 
```
% cn long_type_err_1.c
long_type_err_1.c:2:3: error: Type error
  -1l; 
  ^~~ 
Expected value of type 'i32' but found value of type 'i64'
```

Compare with the following code, which passes CN: 
```
// Passes: 
void a() { 
  1l;  // <-- note no negation 
  return; 
}
```

**Comment by septract** [comment]
Possibly related type error bug: #236

**Comment by dc-mak** [comment]
Possibly related to this too https://github.com/rems-project/cerberus/issues/272

**Comment by cp526** [comment]
Fixed by 6ec601fd2f70e19762de3d0c28274fce9d76f25c

**Comment by dc-mak** [comment]
Can you add regression tests to the test directory for this?

**Comment by cp526** [comment]
There's already some in cn-tutorial

**Comment by dc-mak** [comment]
https://github.com/rems-project/cn-tutorial/commit/3453f6889c53af99f1bfad2f787d413907b8e483
