### ISSUE TITLE
[bug, CN] Unsupported union types

### ISSUE THREAD

**Issue by podhrmic** [rems-project/cerberus#277]
CN verification fails with:

```
/root/.opam/default/lib/cerberus/runtime/libc/include/stdio.h:10:15: error: unsupported union types
typedef union _G_fpos64_t {
              ^~~~~~~~~~~ 
```

See [this CI job](https://github.com/GaloisInc/VERSE-OpenSUT/actions/runs/9305762241/job/25613456635?pr=54#step:4:77) for details, the source file is [actuator.c](https://github.com/GaloisInc/VERSE-OpenSUT/blob/48-verify-mps-in-ci/components/mission_protection_system/src/components/actuator.c), but we see similar error happening with mutiple different input files.

**Comment by podhrmic** [comment]
This is a blocker for us now - see the PR linked above.

**Comment by septract** [comment]
[Deleted as I totally misunderstood the issue]

**Comment by podhrmic** [comment]
I know @peterohanley had some workaround for this, but looks like the new magic syntax has introduced some regression. [This CI job](https://github.com/GaloisInc/VERSE-OpenSUT/actions/runs/9306706276/job/25616448323?pr=54#step:4:77) was passing before I switched the magic syntax,

**Comment by septract** [comment]
Can you isolate the regression? Looking at the diff, the new syntax should not have changed any CN behaviour.

**Comment by podhrmic** [comment]
Good idea. [This commit](https://github.com/GaloisInc/VERSE-OpenSUT/commit/952fd147e3ee5c52af1b4a020b63d854964abb15#diff-dda6c43aff2bbe857f55835e95368d31dbb55bef00afa896a506c8c47850445b) introduced the new special syntax. Can you have a look and see if those changes are sensible?

[The previous commit](https://github.com/GaloisInc/VERSE-OpenSUT/commit/310e48a8cb0334bb77503dfe0ad7a9a4782cb666) had the CN proof for `actuator.c` passing.

[This commit runs the proofs in the CI again](https://github.com/GaloisInc/VERSE-OpenSUT/commit/b09afd7f143b10d922332a431d870d7281aa2ed6)

**Comment by septract** [comment]
Huh yes, that is weird. The minimal failing case is just a file that includes `stdio.h`: 
```C
#include <stdio.h>
```

Gives the following result: 
```
% cn test.c 
/Users/miked/.opam/default/lib/cerberus/runtime/libc/include/stdio.h:10:15: error: unsupported union types
typedef union _G_fpos64_t {
              ^~~~~~~~~~~ 
```

@cp526 Can you look at this? As Michal says, this is a blocker for us. 

(A hypothesis: perhaps there's something important up the dependency tree which is now being skipped because it's wrapped in standard CN comments)

**Comment by dc-mak** [comment]
I'm not sure I follow what's going on. Union types are not supported (yet, in progress) and `#include <stdio.h>` would not have been either, before or after the `--magic-comment-char-dollar` change.

**Comment by dc-mak** [comment]
To double check, I just ran the MWE `#include <stdio.h>` before (c6075bb6886b679dd4578b77617ae15ca42ddbde) and after (60d013553e414522e55994b8f6cf55fa746f47bf) the change, and got the same error both times. 

Is this the correct repro procedure? I wasn't able to repro behaviour.
```
10:25 ➜  src git:(310e48a) cn -I include --include=include/wars.h components/actuator.c
[1/5]: actuate_devices
[2/5]: c_NDEV
[3/5]: c_NVOTE_LOGIC
[4/5]: c_NTRIP
[5/5]: c_NINSTR
10:26 ➜  src git:(310e48a) tig main
10:26 ➜  src git:(310e48a) gco 952fd147e3ee5c52af1b4a020b63d854964abb15
Previous HEAD position was 310e48a CI: run CN from a makefile
HEAD is now at 952fd14 Add Frama-C specs, and switch the CN syntax to /*$
10:26 ➜  src git:(952fd14) cn --magic-comment-char-dollar -I include --include=include/wars.h components/actuator.c
[1/5]: actuate_devices
[2/5]: c_NDEV
[3/5]: c_NVOTE_LOGIC
[4/5]: c_NTRIP
[5/5]: c_NINSTR
10:27 ➜  src git:(952fd14) pwd
/home/dhruv/VERSE-OpenSUT/components/mission_protection_system/src
```

**Comment by septract** [comment]
Okay, I think I'm finally less confused. I think the cause is [this commit](https://github.com/GaloisInc/VERSE-OpenSUT/commit/1ec9df0858b35e16b08f14cc9f513445460a349b) which sets the `PLATFORM_HOST` macro. This has the effect of including `<stdio.h>` [here](https://github.com/GaloisInc/VERSE-OpenSUT/blob/ff395f0c667814f26a09fa61a953edf448b060a0/components/mission_protection_system/src/components/actuator.c#L22). This isn't supported in CN, and has never been. So this change breaks the CN build for the OpenSUT

Conclusion: this is not a CN bug and nothing to do with the new syntax. If we want `<stdio.h>` in the OpenSUT we will need CN to support unions. 

@dc-mak I think you can close this.

**Comment by bcpierce00** [comment]
>
> If we want <stdio.h> in the OpenSUT we will need CN to support unions.
>
I'd love to hear some technical discussion (maybe in a call next week?) of
what's involved in doing this...

**Comment by podhrmic** [comment]
@septract thanks for pointing this out!

I have a workaround in [#59](https://github.com/GaloisInc/VERSE-OpenSUT/pull/59), but being able to use `<stdio.h>` seems pretty important in general.

Where can I find a list of *supported* includes, such that I can properly gate the OpenSUT includes?

**Comment by kmemarian** [comment]
I noticed that the union type wasn't actually needed for the use we have of `fpos_t` in the current state of our libc, so I removed it in 4befd44. And there are no use of unions in headers I believe.
