### ISSUE TITLE
[CN] problem parsing _ExtInt()

### ISSUE THREAD

**Issue by podhrmic** [rems-project/cerberus#279]
Error likely related #278 but different:

```
./src/generated/C/saturation_impl.c:1:26: error: unexpected token after '(' and before '1'
Please add error message for state 382 to parsers/c/c_parser_error.messages
typedef unsigned _ExtInt(1) w1;
                         ^ 
```

**Comment by dc-mak** [comment]
Aside from ExtInt being an unsupported C23 feature, this is just a parser error, and those are easy to update in https://github.com/rems-project/cerberus/blob/master/parsers/c/c_parser_error.messages
