### ISSUE TITLE
[CN] unexpected token after '__attribute__'

### ISSUE THREAD

**Issue by podhrmic** [rems-project/cerberus#284]
CN seems to not recognize compiler attributes,  for example the following code:

```C
static unsigned int boot_once __attribute__ ((section (".tbootdata") ));
```

triggers the following error:
```
firmware.c:20:31: error: unexpected token after '__attribute__' and before '__attribute__'
parsing "typedef_name": seen "LNAME", expecting "TYPE"
static unsigned int boot_once __attribute__ ((section (".tbootdata") ));
                              ^~~~~~~~~~~~~ 
```

This is from the trusted boot code in [OpenSUT](https://github.com/GaloisInc/VERSE-OpenSUT/blob/main/components/platform_crypto/shave_trusted_boot/firmware.c#L20).

**Comment by dc-mak** [comment]
I think such attributes are are not official parts of the ISO specification. A work-around could be to put `#define __attribute__(x) ` in a header and then `--include` that header from the CN command line.

**Comment by kmemarian** [comment]
The cerberus frontend indeed only supports C23 attribute `[[ ... ]]` syntax (modulo the restriction that the payload can only containt string litterals at the moment). The `__attribute__` syntax is a GNU C extension.
