### ISSUE TITLE
[CN] `cn` can't report rich errors in multiple unrelated functions

### ISSUE THREAD

**Issue by samcowger** [rems-project/cerberus#287]
Consider the following code:
```c
int add1(int x)
/*@
requires x == 0i32;
ensures return == 2i32;
@*/
{
    return x + 1;
}

int add3(int x)
/*@
requires x == 0i32;
ensures return == 2i32;
@*/
{
    return x + 3;
}
```

`cn` correctly reports that `add3`'s spec doesn't hold, but doesn't say anything about `add1`, whose spec is also wrong:
```
> cn sample/add1.c
[1/2]: add3
sample/add1.c:16:5: error: Unprovable constraint
    return x + 3;
    ^~~~~~~~~~~~~ 
Constraint from sample/add1.c:13:9:
ensures return == 2i32;
        ^~~~~~~~~~~~~~~
```

 `cn --batch` will report that both functions "fail", but will not report why:
```
> cn --batch sample/add1.c
[1/2]: add3 -- fail
[2/2]: add1 -- fail
summary:
0 pass, 2 fail
```

It would be more user-friendly to be able to report as many errors as richly as possible - in this case, success would look like `cn` reporting both erroneous specs, with their locations, in a single invocation.

(I thought there might already be an issue for this behavior, but I couldn't find one. If there is one, I'm happy to deduplicate and direct conversation there.)

**Comment by septract** [comment]
I might look at this next, unless someone is already looking at it

**Comment by cp526** [comment]
> I might look at this next, unless someone is already looking at it

Sounds good!

**Comment by samcowger** [comment]
I ended up looking into this, and it turns out there is a relatively simple fix to produce multiple errors, under certain circumstances, at the `check.ml` API level. However, I think piping them through to the command line requires resolving a couple of questions:
- CN state files are relatively specialized to exploring a single error. If a user sees multiple errors displayed in the command-line output, should they expect one state file for each of those errors? Should the state file be expanded to support exploring multiple errors? What should be the semantics of the `--state-file` flag in these circumstances?
- How does displaying multiple errors at the command line interact with the existing `--batch` flag? Does multi-error-reporting get hidden behind that flag and replace batch mode, or does batch mode persist and does multi-error become the default?

**Comment by septract** [comment]
Question (1): I think the easiest change is for each error to be a separate state file. Maybe `--state-file` generates `file_1.html`, `file_2.html` ... or something? (I don't know if anyone is relying on `--state-file` at the moment) 

Question (2): maybe there are two orthogonal flags (todo: better names):  
* `--quiet` / `--not-quiet` - does CN report errors, or just success / failure? 
* `--fail-on-first-error` / `--not-fail-on-first-error` - does CN stop when it encounters an error? 

The current `--batch` behavior is `--quiet --not-fail-on-first-error` and the default behavior is `--not-quiet --fail-on-first-error`.

**Comment by cp526** [comment]
@septract Agreed.

If we had those flags, for the command line `--not-quiet` should probably be the default; for the second one it's a bit less clear: it's nice not to overwhelm the user with multiple errors unless they want that, but if it's not the default, the option may also get overlooked.

**Comment by samcowger** [comment]
> Question (1): I think the easiest change is for each error to be a separate state file. Maybe `--state-file` generates `file_1.html`, `file_2.html` ... or something? (I don't know if anyone is relying on `--state-file` at the moment)

That seems reasonable enough, especially if it's unlikely to cause friction with existing users. We might also consider augmenting/replacing it with `--state-dir`, which could fill the provided directory with `1.html`, `2.html`, etc., to ease deletion in case CN ends up generating a ton of those files.

**Comment by samcowger** [comment]
> Question (2): maybe there are two orthogonal flags (todo: better names):
> 
> * `--quiet` / `--not-quiet` - does CN report errors, or just success / failure?
> * `--fail-on-first-error` / `--not-fail-on-first-error` - does CN stop when it encounters an error?
> 
> The current `--batch` behavior is `--quiet --not-fail-on-first-error` and the default behavior is `--not-quiet --fail-on-first-error`.

That sounds reasonable to me. I think that reporting multiple errors should be the default behavior - I may be projecting, but I think a user would more likely find the extra information useful than overwhelming. 

Tactically speaking, I like the name `--quiet`, and for the other I would propose `--fail-fast`, which I feel like I've seen elsewhere. (Also, I'm not sure whether you're proposing this or just illustrating your point, but I'd argue against implementing standalone flags that just set the behavior to the default, like `--not-quiet`.)

**Comment by septract** [comment]
> I'd argue against implementing standalone flags that just set the behavior to the default, like --not-quiet.

Makes sense, I agree.

**Comment by septract** [comment]
> We might also consider augmenting/replacing it with --state-dir, which could fill the provided directory with 1.html, 2.html, etc., to ease deletion in case CN ends up generating a ton of those files.

This is already implemented as `--output-dir`, but it's overridden by `--state-file`. I suggest we just remove `--state-file` altogether
