### ISSUE TITLE
[CN] Configurable output directory

### ISSUE THREAD

**Issue by podhrmic** [rems-project/cerberus#310]
If a proof does not pass, a trace is generated and saved in a temporary directory, e.g.:
```
Consider the state in /tmp/state_0df5d1.html
```

This directory should be configurable, perhaps when `cn` is invoked with `--output-dir SOMEDIR` such that the user can direct where the state information is saved. This would be a nice usability improvement.

**Comment by bcpierce00** [comment]
Another nice improvement would be an option to push the html output into a browser window automatically (by telling a sub shell to 'open' the file) rather than requiring cut and paste.  But I guess all this will be subsumed by the VSCode interface...

**Comment by dc-mak** [comment]
Is `--state-file=FILE` not appropriate for your use cases?

**Comment by podhrmic** [comment]
I wasn't aware of that option! `--state-file` certainly works. Having a specific output directory would be nice, but I am happy to park it as a *someday* feature.

**Comment by septract** [comment]
Addressed by PR #367
