### ISSUE TITLE
[CN] the html output file is written by default to /tmp, where my (default ubuntu) firefox doesn't see it

### ISSUE THREAD

**Issue by PeterSewell** [rems-project/cerberus#325]

**Comment by PeterSewell** [comment]
The problem seems to be that the default ubuntu firefox install now has access only to some of the filesystem - if I manually tell CN to create the file in (e.g.) /home/MYUSERID/tmp it works.  So the default to /tmp is perhaps unhelpful.

**Comment by kmemarian** [comment]
changing the default away from `/tmp` would mean that CN clutter a location the OS doesn't cleanup, which would be quite bad.

maybe we should have a config option?

**Comment by podhrmic** [comment]
Related to #310

**Comment by septract** [comment]
(partially?) addressed by #367

**Comment by septract** [comment]
I suggest we close this as we can now specify the output dir (cc @dc-mak or someone else who has the power to close issues)
