### ISSUE TITLE
[CN] Implement `foo->bar` member syntax for pointers in spec language

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#328]

**Comment by dc-mak** [comment]
Duplicate of https://github.com/rems-project/cerberus/issues/329

**Comment by ZippeyKeys12** [comment]
There isn't a description, but wasn't this issue meant to be about `x->y` being sugar for `(*x).y`?

So not a duplicate of #329?

**Comment by cp526** [comment]
Indeed

**Comment by dc-mak** [comment]
Oops yes thanks

**Comment by septract** [comment]
@dc-mak this issue can be closed
