### ISSUE TITLE
[CN] Feature: add logical implication to the spec language

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#329]
**Currently:** CN's spec language only supports C's ternary conditional operator `B ? P : Q`

**Ideally:** CN should support logical implication `A ==> B` (or whatever symbol we prefer for implication - but I suggest we use `==>` which is the ACSL / FramaC's syntax). 

**How:** Desugar to a ternary conditional, or duplicate and modify the code which supports the ternary conditional. 

This might be an easy first change for someone diving into the CN codebase.

**Comment by elaustell** [comment]
Where is the code that supports the ternary conditional?

**Comment by dc-mak** [comment]
@elaustell it starts here 

https://github.com/rems-project/cerberus/blob/4b3b20632808112b3d30a300825c2109088b53c7/parsers/c/c_parser.mly#L2071

And ends up hitting this

https://github.com/rems-project/cerberus/blob/4b3b20632808112b3d30a300825c2109088b53c7/backend/cn/terms.ml#L78

Though for the sake of location info fidelity it's probably worth just adding it as new construct.

**Comment by elaustell** [comment]
I notice that there is already some support for `impl` in the codebase here
https://github.com/rems-project/cerberus/blob/c6524d280c98163d31efd3eb8ba357576934e397/backend/cn/terms.ml#L192-L193
which appears to have `->` as the impl syntax. However I know @bcpierce00 mentioned using `->` to talk about the fields of structs in ghost code. Should we change the existing support for impl to something like `==>`, or leave what exists unchanged and add something else entirely?

**Comment by cp526** [comment]
Changing it to `==>` sounds like a very good idea.

And regarding adding implication: I had forgotten we internally have a term for implication already; this means this change just needs additions to the frontend.

**Comment by septract** [comment]
@elaustell it sounds like you are going to implement this (thank you!). Once you are done, it would be great to also add some examples of the new syntax to the [example archive](https://github.com/rems-project/cn-tutorial/tree/main/src/example-archive) and/or [tutorial example set](https://github.com/rems-project/cn-tutorial/tree/main/src/examples).

**Comment by elaustell** [comment]
Something else I notice (and maybe the reason it hasn't been implemented yet) is that there are currently two different uses of `Impl` in the code base:
https://github.com/rems-project/cerberus/blob/ec8db7e3173758e3adbecb2dcaebb53e14508f36/backend/absint/src/cfg.ml#L274-L276
Here, `Impl` seems to refer to some sort of implementation. This use of `Impl` is referenced in many other parts of the code base. However, `Impl` is also used in 
https://github.com/rems-project/cerberus/blob/ec8db7e3173758e3adbecb2dcaebb53e14508f36/backend/cn/solver.ml#L794
Here, it refers to implication. There are also many cases of this use of `Impl`. Now that I am adding the implication `Impl` in more places, I am running into errors. Should I change the existing usage of `Impl` as an implication? Or what is the best course of action?

**Comment by kmemarian** [comment]
@cp526 @dc-mak We need to move CN to using it's own lexer before changing to `==>`.

Because this will require adding a new punctuator to the lexer which in the current setup will affect base Cerberus because of CN's reuse of the C lexer. It was fine to add CN keywords because they are in a separated lexicon which we use at runtime just for CN, but we can't do that for punctuators.

**Comment by bcpierce00** [comment]
Maybe we could write it as "implies" for now?  But I'm not sure this
addresses Liz's confusion...

**Comment by kmemarian** [comment]
@bcpierce00 "implies" would indeed work. I started the splitting of C/CN lexers and parsers so we should be able to move to `==>` soon-ish. We need to see how much of the parsing of C type-names we need to duplicate (e.g. do we need arbitrary C constant expressions in the size of C array types written from CN?).

**Comment by kmemarian** [comment]
@elaustell I had a look at your [austell_addImpl](https://github.com/elaustell/cerberus/tree/austell_addImpl) branch, unless I'm misunderstanding the feature request you shouldn't be changing anything to Cabs, Ail or the rest of the pipeline in base Cerberus. You just need the new `CN_impl` you added to `Cn.cn_binop`.

And don't do merge commits of `master` into your branch, you should instead rebase your branch on top of master. Otherwise you won't be able to get your PR into master as the history will not be linear if there were conflicts when merging.

**Comment by dc-mak** [comment]
Just popping in to say thanks to Kayvan, and also confirm that Kayvan is correct. 

https://github.com/rems-project/cerberus/blob/ec8db7e3173758e3adbecb2dcaebb53e14508f36/backend/cn/ONBOARDING.md?plain=1#L34

Thanks for the feature! @elaustell do feel free open [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and request reviews frequently so we can can discuss questions about the code (and I can get notified as a reviewer!)

**Comment by cp526** [comment]
> @bcpierce00 "implies" would indeed work. I started the splitting of C/CN lexers and parsers so we should be able to move to `==>` soon-ish. We need to see how much of the parsing of C type-names we need to duplicate (e.g. do we need arbitrary C constant expressions in the size of C array types written from CN?).

CN parsing of C-types should be the same as in Cerberus base; i expect if we make it less general we’ll sooner or later run into code that needs it. 

Can we not make CN’s parser “import” the whole standard C parser and then build on top (even if that means including expression parsing)?

**Comment by kmemarian** [comment]
@cp526 that makes sense. Menhir has a grammar concatenation feature that would allow us to "import" the C grammar when building CN's, but that requires using the same `token` type for the two grammars (which would mean keeping two version in sync when Cerberus and CN are separated).

I have a first attempt that involves calling the C parser on C type-names from the CN lexer and producing `CTYPE` tokens. This requires a (maybe too hacky? I'm not sure what to think) recovery when the lexer first thought there was a C type-name when in fact it was a `<` relational operator. This seems to work, but if the hack is too offensive, a slight change to the CN syntax would make it go away.

I've created a draft PR #342 so we can move the discussion there.

**Comment by elaustell** [comment]
> Just popping in to say thanks to Kayvan, and also confirm that Kayvan is correct.
> 
> https://github.com/rems-project/cerberus/blob/ec8db7e3173758e3adbecb2dcaebb53e14508f36/backend/cn/ONBOARDING.md?plain=1#L34
> 
> Thanks for the feature! @elaustell do feel free open [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and request reviews frequently so we can can discuss questions about the code (and I can get notified as a reviewer!)

Currently I am unable to rebase on master, I think because I don't have write access to Cerberus? I get the following error: 
```
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by cp526** [comment]
Sorry, that's my bad. I'll send an email now about repository access.

**Comment by kmemarian** [comment]
@elaustell it's probably an issue of remote configuration. What does `git remote -v` show?

**Comment by elaustell** [comment]
> @elaustell it's probably an issue of remote configuration. What does `git remote -v` show?

```
origin  https://github.com/elaustell/cerberus.git (fetch)
origin  https://github.com/elaustell/cerberus.git (push)
upstream        https://github.com/rems-project/cerberus.git (fetch)
upstream        https://github.com/rems-project/cerberus.git (push)
```

**Comment by kmemarian** [comment]
does the following command work?

`git pull --rebase upstream master`

(@dc-mak we probably need to clarify the instructions in ONBOARDING.md)

**Comment by elaustell** [comment]
Yes, that does work, thanks so much! Sorry, I'm not fluent in GitHub quite yet.

**Comment by elaustell** [comment]
@kmemarian I would really like to get `==>` added into CN. Should I go ahead and start changing `Impl` to `Implies` or do you think separating CN out will happen within this week and therefore I should just wait until that happens?

**Comment by dc-mak** [comment]
@elaustell Please feel free to direct any question directly to me via email or Mattermost as a first port of call and we can discuss there :-)
