### ISSUE TITLE
[CN] Use ocamlformat

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#331]
Putting here just for project board.

https://ocaml.org/p/ocamlformat/latest/doc/howtos.html#using-ocamlformat-without-breaking-git-blame

https://ocaml.org/p/ocamlformat/latest/doc/getting_started.html#code-style

https://ocaml.org/p/ocamlformat/latest/doc/getting_started.html#options

**Comment by samcowger** [comment]
Can this be closed, thanks to #403?
