### ISSUE TITLE
[CN] Use subcommands `cn verify`, `cn reify`, `cn lemmas` etc

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#343]
Care needs to be taken so that CI and other scripts are updated simultaneously.
https://github.com/mjambon/cmdliner-cheatsheet?tab=readme-ov-file#subcommands

**Comment by ZippeyKeys12** [comment]
@dc-mak  Shouldn't we make successor issues for pulling out the executable spec and lemma export into their own subcommands as well?

**Comment by dc-mak** [comment]
No-one's working on lemmas right now and so that can be postponed. I suppose we could for executable spec though.
