### ISSUE TITLE
CN installation instructions missing from master

### ISSUE THREAD

**Issue by whyitfor** [rems-project/cerberus#350]
The main README suggestions reading a secondary INSTALL.md to install cn: https://github.com/rems-project/cerberus/blob/master/README.md?plain=1#L180

```
Building CN
---
See https://github.com/rems-project/cerberus/blob/master/backend/cn/INSTALL.md
```

This path does not seem to exist on master. Should this link instead to https://github.com/rems-project/cerberus/tree/master/backend/cn#readme?

**Comment by cp526** [comment]
Thanks, indeed. I just fixed the README.

**Comment by whyitfor** [comment]
Great! This change should probably also propagate to https://rems-project.github.io/cn-tutorial/.

**Comment by cp526** [comment]
Thanks again! Just fixed that.

**Comment by cp526** [comment]
(The tutorial website should be being rebuilt now.)
