### ISSUE TITLE
[CN] CN got more strict on type conversions 

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#376]
(I know the UCam team know about this, but I'm filing a ticket so that we don't forget about it) 

CN version: `git-c142a7ce`

As of today, CN now says [this example](https://github.com/rems-project/cn-tutorial/blob/main/src/example-archive/c-testsuite/broken/error-proof/00111.err1.c) is ill-typed. Previously it passed the type-checker. 
```
int
main()
/*@ ensures return == 0i32; @*/
{
	short s = 1;
	long l = 1;

	s -= l;
	return s;
}
```

With this error: 
```
% cn 00111.err1.c
[1/1]: main
00111.err1.c:8:2: error: Type error
        s -= l;
        ~~^~~~ 
Expected value of type 'i16' but found value of type 'i64'
```

**Comment by kmemarian** [comment]
Fixed by 3594cdb7adef9b6f51c81a3cff02511c684a239f. (And @cp526 as moved the CN-tutorial test back to the success category).
