### ISSUE TITLE
[CN] Elaborate main consistently

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#391]
Copying here: https://github.com/GaloisInc/VERSE-Toolchain/issues/107

Discussed earlier with @kmemarian 

It's not possible to have both (a) consistent types for `main` (b) retain the executability using Cerberus's driver for programs elaborated for CN. This is because the driver requires arguments to be allocated outside the calling function, so that it may be populated with arguments, but for type checking sane specifications, we want arguments to be allocated inside.

For now, we should just sacrifice the ability to execute, and leave a note to explain & revisit this, because this is blocking VERSE project work.

**Comment by cp526** [comment]
@kmemarian AIUI you have an inflight change that fixes `main` in CN but maintains executability? How far away is the fix, or should we, as Dhruv suggests, skip executability for now to more quickly unblock the others?

**Comment by dc-mak** [comment]
@kmemarian updates on this? I believe it's close to done right?

**Comment by kmemarian** [comment]
@dc-mak I've just opened a PR for the fix. It's running the checks

**Comment by kmemarian** [comment]
though the checks won't say whether the issue is fixed. I have tried this:
`cn verify test.c`, on:
``` c
int main(int argc, char* argv[])
{
  return 10;
}
```
is there anything else to check?

**Comment by dc-mak** [comment]
No, I think that's basically it, this was the example on the original issue

```c
//int main(int argc, char **argv) // error
int main(int argc, char *argv[]) // error
//int main(void) // pass
{
  return 0;
}
```

**Comment by cp526** [comment]
Kayvan's 431e3c1 fixes this
