### ISSUE TITLE
CN: Remove Z3 dependency

### ISSUE THREAD

**Issue by cp526** [rems-project/cerberus#411]
Once Cerberus and CN are sufficiently decoupled we should drop CN's dependency on the z3 opam package, in favour of running a downloaded binary, to speed up compilation times.

**Comment by dc-mak** [comment]
Depends on https://github.com/rems-project/cerberus/issues/308

**Comment by dc-mak** [comment]
Completed in https://github.com/rems-project/cerberus/commit/9a1868e611ce53f30e58b910c61e5f25bebf72b6
