### ISSUE TITLE
[CN] Add CI for executable spec

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#417]
Continuation of https://github.com/rems-project/cerberus/issues/343

**Comment by dc-mak** [comment]
@septract is working on this. 
These are related: https://github.com/rems-project/cerberus/pull/439
https://github.com/rems-project/cn-tutorial/commit/115464f217f81ea032144d49e96c3a991cd56861

**Comment by septract** [comment]
See draft PR here: #458

**Comment by dc-mak** [comment]
I reduced the scope of this so I can mark it closed, and moved the remaining tasks to #480.
