### ISSUE TITLE
[CN] feature: allow mention of function pointers with empty parameter lists

### ISSUE THREAD

**Issue by peterohanley** [rems-project/cerberus#438]
```
struct foo {
    int (*bar)();
};
```
```
% cn verify empty_param.c 
empty_param.c:1:1: error: C-type signed int ()*
struct foo {
~~~~~~~^~~~~ 
```

This is holding up TA2 work. We *don't* need to be able to call these functions at this time. I expect calling them will require an ownership that includes an actual type for the pointer.

**Comment by yav** [comment]
I'll have a go at fixing this.  In the meantime, adding an explicit `void` to the parameter list seems to make things work, in case this is an option.

**Comment by cp526** [comment]
@kmemarian comments: as noted on the PR ( https://github.com/rems-project/cerberus/pull/459 ) this isn't completely fixed yet: some change of Cerberus's handling of FunctionNoParams is needed in the frontend.
