### ISSUE TITLE
[CN] Confusing error message for shift right

### ISSUE THREAD

**Issue by lwli11** [rems-project/cerberus#464]
For this minimal function:
```
int shift(int n){
        return n>>2;
}
```

Running CN: >cn verify shr.c
shr.c:2:9: error: PEcall to impl not inlined: SHR_signed_negative
        return n>>2;

Does this mean SHR is implemented or not? Thanks!

**Comment by cp526** [comment]
I think that means it's currently not implemented. Is this blocking you?

**Comment by lwli11** [comment]
Well, I can go verify something else instead, but at some point most of our algorithms will need the basic math operations. I also wanted to point out a confusing error message.

**Comment by cp526** [comment]
Thanks. I've recorded this as a blocking issue.

**Comment by yav** [comment]
I made some progress on this.  The issue is what to do if the left argument is negative (what Cerberus calls `SHR_signed_negative`).   This is implementation define behavior according to the standard.   With the one version I have this is an error, with the other it just does an arithmetic shift.
