### ISSUE TITLE
[CN] Run Docker build nightly 

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#489]
**Problem:** The docker build runs on every PR / commit. This takes a long time, and it makes it annoying to see if the tests have passed (eg. if the job is cancelled manually, we get a CI failure). 

**Proposed resolution:** Build the Docker containers nightly. 

This is a small change: we just change the `.yml` file to use the `schedule` event documented [here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule). 

See [this thread](https://mattermost.galois.com/verse-ta1-ta2/pl/ondrm78oh3b958pxmw9s5j64qo) on MM for discussion. 

cc @podhrmic @dc-mak

**Comment by dc-mak** [comment]
Fixed by https://github.com/rems-project/cerberus/commit/3adb12e7f8f59f87c4494e33fb8bddb975473674 (if I got it right)

**Comment by dc-mak** [comment]
Surprise (!) I had a tiny syntax error that showed up elsewhere but not on the PR itself. Fixed now https://github.com/rems-project/cerberus/commit/8722102c458b0ca03b01f9de66c23ba8ef865180
