### ISSUE TITLE
[CN] Remove `list`, and remove / deprecate other unused keywords

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#490]
**Problem:** 

* CN considers `list` a keyword, but doesn't use it for any current features. See the discussion [here](https://mattermost.galois.com/verse-ta1-ta2/pl/kxkcwbmm37rm7dbfehkf6mb5oe). We would like to free it up for use in examples. 
* CN considers `pack` / `unpack` keywords, but they are not currently hooked up. Using these keywords results in various unhelpful errors, but does not clearly say that these are unimplemented. 
* CN may also include other features that are dead / deprecated - e.g the VSCode plugin marks `tuple` as deprecated. 

**Proposed resolution:**

* Remove `list` as a keyword, and all downstream dead code that results. 
* Keep `pack` / `unpack` as reserved keywords, but on any use, emit an error saying they are unsupported. Remove all downstream dead code that results. 
* Deal with `tuple` and any other keywords by either removing or deprecating them. 

@bcpierce00 @cp526

**Comment by bcpierce00** [comment]
+1

**Comment by dc-mak** [comment]
Finished by https://github.com/rems-project/cerberus/pull/497
