### ISSUE TITLE
[CN] Multithreading

### ISSUE THREAD

**Issue by lwli11** [rems-project/cerberus#535]
Is there any support for multithreading? For example, we have an example code which uses `pthread_mutex_lock`, and we're wondering what's the best way to implement the functions in CN?

Thanks!

**Comment by dc-mak** [comment]
Duplicate: https://github.com/rems-project/cerberus/issues/363

Short answer is no. But, one can emulate a simple discipline with lemmas/specs for that functionality: https://github.com/rems-project/cerberus/issues/363#issuecomment-2214916708 but specialise it for each type of predicate you want to lock/unlock.

```c
mutex *make_mutex(args)
/*@ 
requires 
  take pre = P(args); 
ensures 
  take post_ = P_mutex(return, args); 
@*/

void dup_mutex(args)
/*@ 
requires 
  take pre = P_mutex(return, args);
ensures 
  take post_1 = P_mutex(return, args);
  take post_2 = P_mutex(return, args); 
@*/

take_mutex(mutex *m, args) 
/*@ 
requires 
  take mut = P_mutex(m, args); 
ensures 
  take mut_ = Locked_P_mutex(m, args); 
  take post_ = P(args); 
@*/ 

release_mutex(mutex *m, args) 
/*@ 
requires 
  take locked = Locked_P_mutex(m, args); 
  take inv = P(args); 
ensures 
  take mut_ = P_mutex(m,args); 
@*/ 
```
