### ISSUE TITLE
[CN] `accesses` causes inconsistent assumptions (in loop constructs - for / while) 

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#551]
Using `accesses` introduces inconsistent assumptions eg: 
```
int s; 
void a() 
/*@
  accesses s; 
@*/
{ 
  while ( 1 )  // Same bug with for(;;) 
  {
    ; 
  }
}
```

Calling `cn verify` on this file results in: 
```
error: loop/label makes inconsistent assumptions
  while ( 1 )
  ^~~~~~~~~~~
```

Looking at the resulting state file, I see two copies of the ownership of `&s`. I guess this is the cause of the error: 
<img width="546" alt="Screenshot 2024-09-01 at 4 48 15 PM" src="https://github.com/user-attachments/assets/8117447f-8348-4739-ae42-76fcbef7688a">

CN version: `git-5f6325a8d [2024-08-30 17:02:07 +0100]`

cc @lwli11

**Comment by septract** [comment]
(by the way, CN previously did not produce a state file in this situation, but I updated to the latest version and it now does. That's a very helpful change, thank you!)

**Comment by dc-mak** [comment]
Yeah this one's a real doozy and I spent a few hours investigating last week. There's a discussion here: https://github.com/rems-project/cerberus/issues/399#issuecomment-2321606428 and I can't make sense of the results, so I'm waiting for @cp526 to return and take a look.

**Comment by lwli11** [comment]
Interesting! Glad to find a real bug finally!

**Comment by podhrmic** [comment]
@septract FYI this is one of the blocking issues

**Comment by septract** [comment]
@podhrmic good to know, sounds like this is also blocked on the Cambridge side until @cp526 gets back

**Comment by cp526** [comment]
This should be fixed by https://github.com/rems-project/cerberus/pull/565 (please re-open if not!).

**Comment by septract** [comment]
@cp526 I think you should also include the above code or something like it as a test that should succeed. The fix you've made doesn't add a test that would catch this error
