### ISSUE TITLE
[CN] Variable names can't be function names?

### ISSUE THREAD

**Issue by lwli11** [rems-project/cerberus#553]
The following code looks valid to gcc, but I get an error: `var_name.h:8:23: error: redeclaration of variable
/*@ spec example2(i32 example1);`

```c
extern void example1(int i);
/*@ spec example1(i32 i);
        requires true;
        ensures true;
@*/

extern void example2(int example1);
/*@ spec example2(i32 example1);
        requires true;
        ensures true;
@*/
```

Is the problem the fact that you can't use function names as variable names? I don't remember seeing anything in the tutorial.

Thanks again!

**Comment by peterohanley** [comment]
Looks like #316. CN has different and as you see here sometimes incompatible rules for scope.

**Comment by dc-mak** [comment]
@lwli11 you may find this helpful to get the formatting you desire 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by dc-mak** [comment]
Duplicate: #316 (thanks @peterohanley!)
