### ISSUE TITLE
Member shift fails inside resource predicates

### ISSUE THREAD

**Issue by thatplguy** [rems-project/cerberus#615]
The member shift operation seems to fail inside predicate definitions while working in function specs.  Maybe because CN looks to parameters to find types rather than the type annotation in the `Owned<T>` resource predicate?

Failing example:
```
/*@
datatype Point {Point {i32 x, i32 y}}

// Assumes points are represented as 2-element arrays.
predicate (Point) Point_At(pointer p) {
    take array_in = each (u64 i; i < 2u64) {Owned<int>(p + i)};  // error on p + i
    let x_in = array_in[0];
    let y_in = array_in[1];
    return Point {x: x_in, y: y_in};
}
@*/
```

Error: 
`Cannot tell pointee C-type of 'p'.`

Cerberus/CN version:
`git-13c264c52 [2024-10-06 19:32:33 +0100]`

**Comment by peterohanley** [comment]
You don't actually use any member shift operation here, just pointer arithmetic on a raw pointer. Owned<int> is the type of the result and not type type of `p` here. You need to do `array_shift<int>(p,i)` like so:
```
/*@
datatype Point {Point {i32 x, i32 y}}

// Assumes points are represented as 2-element arrays.
predicate (Point) Point_At(pointer p) {
    take array_in = each (u64 i; i < 2u64) {Owned<int>(array_shift<int>(p,i))};
    let x_in = array_in[0u64];
    let y_in = array_in[1u64];
    return Point {x: x_in, y: y_in};
}
@*/
```

**Comment by thatplguy** [comment]
Thanks @peterohanley.  As you say, I'd mistakenly thought the type of the element being claimed in an array should guide the typing of the array, but they are indeed orthogonal.
