### ISSUE TITLE
[CN] No solution found at opam install --deps-only step

### ISSUE THREAD

**Issue by r-ross** [rems-project/cerberus#627]
Following <https://github.com/rems-project/cerberus/blob/master/backend/cn/README.md> on an Ubuntu Focal VM failed at step 5:
```
$ opam install --deps-only ./cerberus-lib.opam ./cn.opam
[WARNING] Failed checks on cn package definition from source at git+file:///home.local/savve/cerberus#master:
  warning 25: Missing field 'authors'
  warning 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
```

From a new virtual machine where
```
$ head -n2 /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
- Run `sudo useradd -d /home.local/savve -g savve-users -m -s /bin/bash savve` and then `sudo su - savve` to switch to the new user. This step may not be necessary and `-g savve-users` may be omitted.
- Run `sudo apt-get install opam` to install OPAM 2.0.5.
- Run `opam init -y` followed by `eval $(opam env)`.
- Run `opam install ocaml-lsp-server odoc ocamlformat utop` as mentioned at <https://ocaml.org/docs/installing-ocaml>.  I suspect this step helped trigger the problem.
- Run `sudo apt install libgmp-dev libmpfr-dev python2.7` for Python2 2.7.18 (in addition to Python3 3.8.10).
- Run `opam install dune lem` for Lem 2022-12-10 (Dune 3.16.0 was already installed by the commands above).
- Run `git clone https://github.com/rems-project/cerberus.git` and `cd cerberus`.
- Run `opam install --deps-only ./cerberus-lib.opam ./cn.opam` for the problem mentioned above.  Its failure prevents `make install_cn` from working.

I tried commands such as `git checkout a91db76c` for an older version (from 2024-07-24) but kept getting the same problem.  Please let me know if you need more information to reproduce the issue.

**Comment by dc-mak** [comment]
What version of opam do you have?

**Comment by r-ross** [comment]
As mentioned in the second bullet, `opam --version` is `2.0.5`.  As shown in <https://packages.ubuntu.com/focal/opam>, that is still the latest version from the Ubuntu package manager.

**Comment by dc-mak** [comment]
Apologies, and thank you. The opam version is quite old, and if you can use a more up-to-date one, that would give a more helpful error message https://discuss.ocaml.org/t/sorry-no-solution-found-there-seems-to-be-a-problem-with-your-request/8443/5

Retrying with the latest version might give a more informative error message: 
```sh 
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
```

**Comment by dc-mak** [comment]
Hi, I set up an Ubuntu machine and followed the steps you helpfully listed above. 

By default the OCaml version that it installs is 4.08.1. 

In the README, the first step is:

> Install a recent version of OCaml (we are using 5.0.0 -- 5.2.0) and the opam package manager for OCaml, following the instructions at https://ocaml.org/docs/install.html. (Remember to initialise opam via opam init after the installation of opam.)

There's room to for improvement in clarity (our apologies), but the intention there is that people install an up-to-date opam and OCaml as the first step.

The error you get is because we CN only supports OCaml versions 4.14.1 and later, so there's no way for opam to satisfy that dependency under the current compiler switch.

```sh
dhruv@Gandiva:~/cerberus$ opam install -vvv --deps-only ./cerberus-lib.opam ./cn.opam
+ /usr/bin/git "symbolic-ref" "--quiet" "--short" "HEAD"
- master
+ /usr/bin/git "symbolic-ref" "--quiet" "--short" "HEAD"
- master
+ /usr/bin/lsb_release "-s" "-r"
- 20.04
+ /usr/bin/ocamlc "-vnum"
- 4.08.1
[WARNING] Failed checks on cn package definition from source at git+file:///home/dhruv/cerberus#master:
  warning 25: Missing field 'authors'
  warning 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
'opam install -vvv --deps-only ./cerberus-lib.opam ./cn.opam' failed.
```

https://github.com/rems-project/cerberus/blob/0ef1e7075079a5befb4d02e8a156e9ad8fcd76c0/cn.opam#L8

If you run the line

```sh
opam switch create 4.14.1
```

before doing any `opam install` commands, everything should work out fine.

**Comment by r-ross** [comment]
Thanks!  Using `opam switch create 4.14.1` worked without upgrading `opam`.  I recommend mentioning it, possibly with a replacement for `4.14.1`, in step 1 of <https://github.com/rems-project/cerberus/blob/master/backend/cn/README.md> since it's not mentioned in <https://ocaml.org/docs/installing-ocaml> and since it's mentioned in other install instructions such as <https://git.frama-c.com/pub/frama-c/blob/master/INSTALL.md>.  Also, while modifying `cn/README.md`, consider removing the "Funding Acknowledgements" section until content is available.

**Comment by dc-mak** [comment]
The README was written in a rush. I will update when I have time. PRs welcome.
