### ISSUE TITLE
Better error message for undefined types

### ISSUE THREAD

**Issue by lwli11** [rems-project/cerberus#631]
Is it possible to explicitly notify the user when a type is not declared yet instead of something like "error: unexpected token after 'uint32_t' and before 'uint32_t'
parsing "typedef_name": seen "LNAME", expecting "TYPE""

Thanks!

**Comment by dc-mak** [comment]
Anyone can add custom error messages to parsers/c/c_parser_error.messages very easily, so we welcome PRs for it
