### ISSUE TITLE
Unsequenced side effects

### ISSUE THREAD

**Issue by victorgomes** [rems-project/cerberus#66]
```c
int foo (int *p1, int *p2) {
	return (*p1)++ + (*p2)++;
}

int main (void) {
      int x = 2;
      int result = (x = 1) + (x = 2);
	int a = 0;
	foo (&a, &a);
	return 0;
}
```
This should be undefined behaviour according to 6.5#2:
> If a side effect on a scalar object is unsequenced relative to either a different side effect on the same scalar object or a value computation using the value of the same scalar object, the behavior is undefined.

**Comment by kmemarian** [comment]
this was fixed for the sequential mode with the new Core dynamics
